version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: j01676705370
      MYSQL_DATABASE: uxpon
      MYSQL_USER: uxpon
      MYSQL_PASSWORD: j01676705370
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
